name: Build Redmi2 Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc \
            bison \
            build-essential \
            flex \
            git \
            libelf-dev \
            libssl-dev \
            gcc-8 \
            g++-8 \
            gcc-8-arm-linux-gnueabi \
            binutils-arm-linux-gnueabi

      - name: Set GCC 8
        run: |
          echo "CC=gcc-8" >> $GITHUB_ENV
          echo "HOSTCC=gcc-8" >> $GITHUB_ENV

      - name: Configure
        run: |
          mkdir -p out
          make O=out \
            ARCH=arm \
            CROSS_COMPILE=arm-linux-gnueabi- \
            lineageos_wt88047_defconfig

      - name: Build Kernel
        run: |
          make -j2 \
            O=out \
            ARCH=arm \
            CROSS_COMPILE=arm-linux-gnueabi- \
            HOSTCC=gcc-8 \
            HOSTCXX=g++-8

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Redmi2-Kernel
          path: |
            out/arch/arm/boot/zImage
            out/arch/arm/boot/dts/
