name: Build Redmi2 Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          bc \
          bison \
          build-essential \
          ccache \
          flex \
          git \
          libssl-dev \
          libelf-dev \
          gcc-arm-linux-gnueabi \
          python2

    - name: Configure kernel
      run: |
        mkdir -p out
        make O=out ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- lineageos_wt88047_defconfig

    - name: Build kernel
      env:
        HOSTCFLAGS: -fcommon
      run: |
        make -j$(nproc) \
          O=out \
          ARCH=arm \
          CROSS_COMPILE=arm-linux-gnueabi-

    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-Image
        path: |
          out/arch/arm/boot/zImage
          out/arch/arm/boot/Image*
          out/arch/arm/boot/dts/**/*.dtb
